apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    releaseName: grafana
    version: 7.3.7
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
